[package]
name = "promptify"
version = "0.1.5"
edition = "2021"
description = "A plaintext directory formatting tool for interacting with LLMs on the command line."
license = "MIT"

[dependencies]
clap = "4.5.26"
glob = "0.3.2"
mime_guess = "2.0.5"
walkdir = "2.5.0"
